from django.contrib.auth import views as auth_views
from django.urls import path

from . import billing_views, views

app_name = 'crm'

urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='crm/login.html'),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path('onboarding/<uuid:token>/', views.onboarding_form, name='onboarding_form'),
    path(
        'onboarding/<uuid:token>/section/',
        views.onboarding_section_save,
        name='onboarding_section_save',
    ),
    path(
        'onboarding/<uuid:token>/submit/',
        views.onboarding_final_submit,
        name='onboarding_final_submit',
    ),
    path('portal/<uuid:token>/', views.client_portal, name='client_portal'),
    path(
        'portal/<uuid:token>/change-request/',
        views.portal_submit_change_request,
        name='portal_submit_change_request',
    ),
    path(
        'portal/<uuid:token>/change-requests/',
        views.portal_change_requests,
        name='portal_change_requests',
    ),
    path('', views.dashboard, name='dashboard'),
    path('operations/', views.operations_dashboard, name='operations_dashboard'),
    path('projects/', views.projects_list, name='projects'),
    path('projects/create/', views.project_create, name='project_create'),
    path('projects/<int:pk>/', views.project_detail, name='project_detail'),
    path(
        'projects/<int:pk>/operations/',
        views.project_operations,
        name='project_operations',
    ),
    path(
        'projects/<int:pk>/operations/provisioning/',
        views.project_provisioning_step_update,
        name='project_provisioning_step',
    ),
    path(
        'projects/<int:pk>/operations/credentials/',
        views.project_credential_save,
        name='project_credential_save',
    ),
    path(
        'projects/<int:pk>/operations/credentials/<int:cred_id>/reveal/',
        views.credential_reveal,
        name='credential_reveal',
    ),
    path(
        'projects/<int:pk>/operations/credentials/<int:cred_id>/copy-log/',
        views.credential_copy_logged,
        name='credential_copy_logged',
    ),
    path(
        'projects/<int:pk>/operations/handover/',
        views.project_handover_save,
        name='project_handover_save',
    ),
    path(
        'projects/<int:pk>/operations/renewals/',
        views.project_renewal_add,
        name='project_renewal_add',
    ),
    path(
        'projects/<int:pk>/portal/activate/',
        views.portal_activate,
        name='portal_activate',
    ),
    path(
        'projects/<int:pk>/portal/deactivate/',
        views.portal_deactivate,
        name='portal_deactivate',
    ),
    path(
        'projects/<int:pk>/status/',
        views.project_status_update,
        name='project_status_update',
    ),
    path(
        'projects/<int:pk>/onboarding/',
        views.project_onboarding_detail,
        name='project_onboarding_detail',
    ),
    path(
        'projects/<int:pk>/onboarding/section/verify/',
        views.onboarding_section_verify,
        name='onboarding_section_verify',
    ),
    path(
        'projects/<int:pk>/onboarding/notes/',
        views.onboarding_internal_notes_save,
        name='onboarding_internal_notes_save',
    ),
    path(
        'projects/<int:pk>/onboarding/client-notes/',
        views.onboarding_client_notes_save,
        name='onboarding_client_notes_save',
    ),
    path('leads/', views.leads_list, name='leads'),
    path('leads/more/', views.leads_more_json, name='leads_more'),
    path('leads/search/', views.lead_search, name='lead_search'),
    path('leads/quick-add/', views.lead_quick_add, name='lead_quick_add'),
    path('leads/create/', views.lead_create, name='lead_create'),
    path('leads/import/', views.leads_import_excel, name='leads_import'),
    path('leads/<int:pk>/patch/', views.lead_patch, name='lead_patch'),
    path('leads/<int:pk>/quick-fu/', views.lead_quick_followup, name='lead_quick_fu'),
    path('leads/<int:pk>/quick-note/', views.lead_quick_note, name='lead_quick_note'),
    path(
        'leads/<int:lead_pk>/convert/',
        views.lead_convert_to_project,
        name='lead_convert',
    ),
    path('leads/<int:pk>/', views.lead_detail, name='lead_detail'),
    path('leads/<int:pk>/notes/', views.lead_notes_save, name='lead_notes_save'),
    path(
        'leads/<int:pk>/contact/',
        views.lead_contact_save,
        name='lead_contact_save',
    ),
    path('leads/<int:pk>/status/', views.lead_status_detail, name='lead_status_detail'),
    path('leads/<int:lead_pk>/followup/', views.followup_add, name='followup_add'),
    path('leads/<int:lead_pk>/task/', views.task_add, name='task_add'),
    path(
        'leads/<int:pk>/tasks-panel/',
        views.lead_tasks_panel,
        name='lead_tasks_panel',
    ),
    path('leads/<int:pk>/log-call/', views.lead_log_call, name='lead_log_call'),
    path(
        'leads/<int:pk>/log-whatsapp/',
        views.lead_log_whatsapp,
        name='lead_log_whatsapp',
    ),
    path('tasks/<int:pk>/toggle/', views.task_toggle, name='task_toggle'),
    path('tasks/<int:pk>/update/', views.task_update, name='task_update'),
    path(
        'header/tasks-dropdown/',
        views.tasks_header_dropdown,
        name='tasks_header_dropdown',
    ),
    path(
        'header/tasks-badges/',
        views.tasks_header_badges,
        name='tasks_header_badges',
    ),
    path('followups/', views.followups_page, name='followups'),
    path('followups/<int:pk>/done/', views.followup_done, name='followup_done'),
    path('followups/<int:pk>/reschedule/', views.followup_reschedule, name='followup_reschedule'),
    path('packages/', views.packages_page, name='packages'),
    path('packages/create/', views.package_create, name='package_create'),
    path('packages/<int:pk>/edit/', views.package_update, name='package_update'),
    path('packages/<int:pk>/delete/', views.package_delete, name='package_delete'),
    path('packages/<int:pk>/scope/', views.package_scope_edit, name='package_scope_edit'),
    path('performance/', views.performance, name='performance'),
    path(
        'performance/report-card/',
        views.performance_report_card,
        name='performance_report_card',
    ),
    path(
        'leads/<int:pk>/high-hope-toggle/',
        views.lead_high_hope_toggle,
        name='lead_high_hope_toggle',
    ),
    path('achievements/', views.achievements_dashboard, name='achievements_dashboard'),
    path('achievements/create/', views.achievement_create, name='achievement_create'),
    path('achievements/<int:pk>/edit/', views.achievement_update, name='achievement_update'),
    path('achievements/<int:pk>/delete/', views.achievement_delete, name='achievement_delete'),
    path('audit/', views.audit_trail, name='audit_trail'),
    path('projects/<int:pk>/audit/', views.project_audit_trail, name='project_audit_trail'),
    path(
        'projects/<int:pk>/change-request/staff/',
        views.change_request_staff_create,
        name='change_request_staff_create',
    ),
    path('change-requests/', views.change_requests_list, name='change_requests_list'),
    path(
        'change-requests/<int:pk>/',
        views.change_request_detail,
        name='change_request_detail',
    ),
    path(
        'change-requests/<int:pk>/triage/',
        views.change_request_triage,
        name='change_request_triage',
    ),
    path(
        'change-requests/<int:pk>/quote/',
        views.change_request_quote,
        name='change_request_quote',
    ),
    path(
        'change-requests/<int:pk>/approve/',
        views.change_request_approve,
        name='change_request_approve',
    ),
    path(
        'change-requests/<int:pk>/reject/',
        views.change_request_reject,
        name='change_request_reject',
    ),
    path(
        'change-requests/<int:pk>/complete/',
        views.change_request_complete,
        name='change_request_complete',
    ),
    path(
        'change-requests/<int:pk>/start/',
        views.change_request_start,
        name='change_request_start',
    ),
    path('renewals/', views.renewals_dashboard, name='renewals_dashboard'),
    path('renewals/<int:pk>/', views.renewal_detail, name='renewal_detail'),
    path(
        'renewals/<int:pk>/send-reminder/',
        views.renewal_send_reminder_manual,
        name='renewal_send_reminder_manual',
    ),
    # Billing & Accounts (admin only)
    path('billing/', billing_views.billing_dashboard, name='billing_dashboard'),
    path('billing/ledger/', billing_views.ledger_list, name='billing_ledger'),
    path('billing/projects/<int:pk>/', billing_views.billing_project, name='billing_project'),
    path('billing/projects/<int:pk>/record/', billing_views.billing_project, name='billing_record'),
    path('billing/projects/<int:pk>/bills/create/', billing_views.bill_create, name='bill_create'),
    path(
        'billing/projects/<int:pk>/bills/quick/',
        billing_views.bill_quick_create,
        name='bill_quick_create',
    ),
    path('billing/projects/<int:pk>/payments/', billing_views.payment_create, name='payment_create'),
    path(
        'billing/projects/<int:pk>/statement/',
        billing_views.statement_download,
        name='statement_download',
    ),
    path('billing/bills/<int:pk>/', billing_views.bill_detail, name='bill_detail'),
    path('billing/bills/<int:pk>/pdf/', billing_views.bill_pdf, name='bill_pdf'),
    path(
        'billing/bills/<int:pk>/resend-email/',
        billing_views.bill_resend_email,
        name='bill_resend_email',
    ),
    path(
        'billing/payments/<int:payment_pk>/verify/',
        billing_views.payment_verify,
        name='payment_verify',
    ),
    path(
        'billing/payments/<int:payment_pk>/pdf/',
        billing_views.payment_receipt_pdf,
        name='payment_receipt_pdf',
    ),
    path(
        'billing/payments/<int:payment_pk>/resend-email/',
        billing_views.payment_resend_email,
        name='payment_resend_email',
    ),
]
